# Generated by Django 5.2.3 on 2025-07-21 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle_totp', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('date_derniere_validation', models.DateTimeField(blank=True, null=True)),
                ('appareil_confirme', models.CharField(blank=True, max_length=200, null=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_2fa', to='etablissement.utilisateur')),
            ],
        ),
    ]
