# Generated by Django 5.2.3 on 2025-07-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_lue', models.BooleanField(default=False)),
                ('lien_associe', models.CharField(blank=True, max_length=255)),
                ('type_notification', models.CharField(blank=True, choices=[('message', 'Message privé'), ('annonce', 'Annonce urgente'), ('forum', 'Forum')], default='message', max_length=30)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='etablissement.utilisateur')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
