# Generated by Django 5.2.3 on 2025-07-26 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('prive', 'Privé'), ('section', 'Section'), ('departement', 'Departement')], max_length=20),
        ),
    ]
