# Generated by Django 5.2.3 on 2025-07-26 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_message_is_deleted_alter_message_type_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date_lecture',
        ),
        migrations.RemoveField(
            model_name='message',
            name='est_lu',
        ),
        migrations.CreateModel(
            name='MessageUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_lu', models.BooleanField(default=False)),
                ('est_supprime', models.BooleanField(default=False)),
                ('est_en_corbeille', models.BooleanField(default=False)),
                ('est_favori', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.message')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etablissement.utilisateur')),
            ],
            options={
                'unique_together': {('message', 'utilisateur')},
            },
        ),
    ]
