# Generated by Django 5.2.3 on 2025-07-18 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paiement',
            options={'ordering': ['-date_paiement'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.AddField(
            model_name='enseignant',
            name='enseignant_diplomes',
            field=models.FileField(blank=True, upload_to='enseignant_diplomes/'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='enseignant_photo',
            field=models.ImageField(blank=True, default='enseignant_photo/default.png', upload_to='enseignant_photo/'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='enseignant_telephone',
            field=models.CharField(default='+224628928999', max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide.', regex='^\\+?\\d{9,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='etudiant_photo',
            field=models.ImageField(blank=True, default='photo_etudiant/default.png', upload_to='photo_etudiant/'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='telephone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numéro invalide.', regex='^\\+?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement', to='etablissement.departement'),
        ),
    ]
