# Generated by Django 5.2.3 on 2025-07-26 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0003_remove_message_date_lecture_remove_message_est_lu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
    ]
