# Generated by Django 5.2.3 on 2025-08-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0004_remove_message_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='type_fichier',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
